### PR TITLE
Use commit hash for the ncipollo/release-action for sec reasons

### PR DESCRIPTION
**Pull request by bradjohnl**
Implementing security best practice.
More info: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

### CODE REVIEW

**Review by sacherjj — APPROVED** [review]

**Comment by sacherjj** [comment]
We also need to PR this change to casper, casper-test, and integration-test branches as they don't get merged to from main.

**Comment by bradjohnl** [comment]
@sacherjj Ok, will create it for those branches as well

**Comment by bradjohnl** [comment]
@sacherjj I think this can be a new use-case for a workflow involving the sync-branches action.
We could have it trigger so that PRs targeting main gets mirrored to those 3 branches automatically.

This is the implementation I did for the docs gitflow where we need to keep dev and main in sync:
https://github.com/casper-network/docs/blob/dev/.github/workflows/dev_main_sync.yml

**Comment by sacherjj** [comment]
We would never want to sync config directory, casper-node_release, and protocol_versions.  But everything else would probably want to flow through.

**Pull request merged**
